
// TODO: use allFactoryFunctions or cleanup
// const allFactoryFunctions = {
//   createResultSet: 'Function',
//   createBigNumberClass: 'Function',
//   createComplexClass: 'Function',
//   createFractionClass: 'Function',
//   createRangeClass: 'Function',
//   createMatrixClass: 'Function',
//   createDenseMatrixClass: 'Function',
//   createClone: 'Function',
//   createIsInteger: 'Function',
//   createIsNegative: 'Function',
//   createIsNumeric: 'Function',
//   createHasNumericValue: 'Function',
//   createIsPositive: 'Function',
//   createIsZero: 'Function',
//   createIsNaN: 'Function',
//   createTypeOf: 'Function',
//   createTyped: 'Function',
//   createDeprecatedTypeof: 'Function',
//   createEqualScalar: 'Function',
//   createSparseMatrixClass: 'Function',
//   createNumber: 'Function',
//   createString: 'Function',
//   createBoolean: 'Function',
//   createBignumber: 'Function',
//   createComplex: 'Function',
//   createFraction: 'Function',
//   createMatrix: 'Function',
//   createSplitUnit: 'Function',
//   createUnaryMinus: 'Function',
//   createUnaryPlus: 'Function',
//   createAbs: 'Function',
//   createAddScalar: 'Function',
//   createCbrt: 'Function',
//   createCeil: 'Function',
//   createCube: 'Function',
//   createExp: 'Function',
//   createExpm1: 'Function',
//   createFix: 'Function',
//   createFloor: 'Function',
//   createGcd: 'Function',
//   createLcm: 'Function',
//   createLog10: 'Function',
//   createLog2: 'Function',
//   createMod: 'Function',
//   createMultiplyScalar: 'Function',
//   createMultiply: 'Function',
//   createNthRoot: 'Function',
//   createSign: 'Function',
//   createSqrt: 'Function',
//   createSquare: 'Function',
//   createSubtract: 'Function',
//   createXgcd: 'Function',
//   createDotMultiply: 'Function',
//   createBitAnd: 'Function',
//   createBitNot: 'Function',
//   createBitOr: 'Function',
//   createBitXor: 'Function',
//   createArg: 'Function',
//   createConj: 'Function',
//   createIm: 'Function',
//   createRe: 'Function',
//   createNot: 'Function',
//   createOr: 'Function',
//   createXor: 'Function',
//   createConcat: 'Function',
//   createCross: 'Function',
//   createDiag: 'Function',
//   createEye: 'Function',
//   createFilter: 'Function',
//   createFlatten: 'Function',
//   createForEach: 'Function',
//   createGetMatrixDataType: 'Function',
//   createIdentity: 'Function',
//   createKron: 'Function',
//   createMap: 'Function',
//   createOnes: 'Function',
//   createRange: 'Function',
//   createReshape: 'Function',
//   createResize: 'Function',
//   createSize: 'Function',
//   createSqueeze: 'Function',
//   createSubset: 'Function',
//   createTranspose: 'Function',
//   createCtranspose: 'Function',
//   createZeros: 'Function',
//   createErf: 'Function',
//   createMode: 'Function',
//   createProd: 'Function',
//   createFormat: 'Function',
//   createPrint: 'Function',
//   createTo: 'Function',
//   createIsPrime: 'Function',
//   createNumeric: 'Function',
//   createDivideScalar: 'Function',
//   createPow: 'Function',
//   createRound: 'Function',
//   createLog: 'Function',
//   createLog1p: 'Function',
//   createNthRoots: 'Function',
//   createDotPow: 'Function',
//   createDotDivide: 'Function',
//   createLsolve: 'Function',
//   createUsolve: 'Function',
//   createLeftShift: 'Function',
//   createRightArithShift: 'Function',
//   createRightLogShift: 'Function',
//   createAnd: 'Function',
//   createCompare: 'Function',
//   createCompareNatural: 'Function',
//   createCompareText: 'Function',
//   createEqual: 'Function',
//   createEqualText: 'Function',
//   createSmaller: 'Function',
//   createSmallerEq: 'Function',
//   createLarger: 'Function',
//   createLargerEq: 'Function',
//   createDeepEqual: 'Function',
//   createUnequal: 'Function',
//   createPartitionSelect: 'Function',
//   createSort: 'Function',
//   createMax: 'Function',
//   createMin: 'Function',
//   createImmutableDenseMatrixClass: 'Function',
//   createIndexClass: 'Function',
//   createFibonacciHeapClass: 'Function',
//   createSpaClass: 'Function',
//   createUnitClass: 'Function',
//   createUnit: 'Function',
//   createSparse: 'Function',
//   createCreateUnit: 'Function',
//   createAcos: 'Function',
//   createAcosh: 'Function',
//   createAcot: 'Function',
//   createAcoth: 'Function',
//   createAcsc: 'Function',
//   createAcsch: 'Function',
//   createAsec: 'Function',
//   createAsech: 'Function',
//   createAsin: 'Function',
//   createAsinh: 'Function',
//   createAtan: 'Function',
//   createAtan2: 'Function',
//   createAtanh: 'Function',
//   createCos: 'Function',
//   createCosh: 'Function',
//   createCot: 'Function',
//   createCoth: 'Function',
//   createCsc: 'Function',
//   createCsch: 'Function',
//   createSec: 'Function',
//   createSech: 'Function',
//   createSin: 'Function',
//   createSinh: 'Function',
//   createTan: 'Function',
//   createTanh: 'Function',
//   createSetCartesian: 'Function',
//   createSetDifference: 'Function',
//   createSetDistinct: 'Function',
//   createSetIntersect: 'Function',
//   createSetIsSubset: 'Function',
//   createSetMultiplicity: 'Function',
//   createSetPowerset: 'Function',
//   createSetSize: 'Function',
//   createSetSymDifference: 'Function',
//   createSetUnion: 'Function',
//   createAdd: 'Function',
//   createHypot: 'Function',
//   createNorm: 'Function',
//   createDot: 'Function',
//   createTrace: 'Function',
//   createIndex: 'Function',
//   createNode: 'Function',
//   createAccessorNode: 'Function',
//   createArrayNode: 'Function',
//   createAssignmentNode: 'Function',
//   createBlockNode: 'Function',
//   createConditionalNode: 'Function',
//   createConstantNode: 'Function',
//   createFunctionAssignmentNode: 'Function',
//   createIndexNode: 'Function',
//   createObjectNode: 'Function',
//   createOperatorNode: 'Function',
//   createParenthesisNode: 'Function',
//   createRangeNode: 'Function',
//   createRelationalNode: 'Function',
//   createSymbolNode: 'Function',
//   createFunctionNode: 'Function',
//   createParse: 'Function',
//   createCompile: 'Function',
//   createEvaluate: 'Function',
//   createDeprecatedEval: 'Function',
//   createParserClass: 'Function',
//   createParser: 'Function',
//   createLup: 'Function',
//   createQr: 'Function',
//   createSlu: 'Function',
//   createLusolve: 'Function',
//   createHelpClass: 'Function',
//   createChainClass: 'Function',
//   createHelp: 'Function',
//   createChain: 'Function',
//   createDet: 'Function',
//   createInv: 'Function',
//   createExpm: 'Function',
//   createSqrtm: 'Function',
//   createDivide: 'Function',
//   createDistance: 'Function',
//   createIntersect: 'Function',
//   createSum: 'Function',
//   createMean: 'Function',
//   createMedian: 'Function',
//   createMad: 'Function',
//   createVariance: 'Function',
//   createDeprecatedVar: 'Function',
//   createQuantileSeq: 'Function',
//   createStd: 'Function',
//   createCombinations: 'Function',
//   createGamma: 'Function',
//   createFactorial: 'Function',
//   createKldivergence: 'Function',
//   createMultinomial: 'Function',
//   createPermutations: 'Function',
//   createPickRandom: 'Function',
//   createRandom: 'Function',
//   createRandomInt: 'Function',
//   createStirlingS2: 'Function',
//   createBellNumbers: 'Function',
//   createCatalan: 'Function',
//   createComposition: 'Function',
//   createSimplify: 'Function',
//   createDerivative: 'Function',
//   createRationalize: 'Function',
//   createReviver: 'Function',
//   createE: 'Function',
//   createUppercaseE: 'Function',
//   createFalse: 'Function',
//   createI: 'Function',
//   createInfinity: 'Function',
//   createLN10: 'Function',
//   createLN2: 'Function',
//   createLOG10E: 'Function',
//   createLOG2E: 'Function',
//   createNaN: 'Function',
//   createNull: 'Function',
//   createPhi: 'Function',
//   createPi: 'Function',
//   createUppercasePi: 'Function',
//   createSQRT1_2: 'Function',
//   createSQRT2: 'Function',
//   createTau: 'Function',
//   createTrue: 'Function',
//   createVersion: 'Function',
//   createAtomicMass: 'Function',
//   createAvogadro: 'Function',
//   createBohrMagneton: 'Function',
//   createBohrRadius: 'Function',
//   createBoltzmann: 'Function',
//   createClassicalElectronRadius: 'Function',
//   createConductanceQuantum: 'Function',
//   createCoulomb: 'Function',
//   createDeuteronMass: 'Function',
//   createEfimovFactor: 'Function',
//   createElectricConstant: 'Function',
//   createElectronMass: 'Function',
//   createElementaryCharge: 'Function',
//   createFaraday: 'Function',
//   createFermiCoupling: 'Function',
//   createFineStructure: 'Function',
//   createFirstRadiation: 'Function',
//   createGasConstant: 'Function',
//   createGravitationConstant: 'Function',
//   createGravity: 'Function',
//   createHartreeEnergy: 'Function',
//   createInverseConductanceQuantum: 'Function',
//   createKlitzing: 'Function',
//   createLoschmidt: 'Function',
//   createMagneticConstant: 'Function',
//   createMagneticFluxQuantum: 'Function',
//   createMolarMass: 'Function',
//   createMolarMassC12: 'Function',
//   createMolarPlanckConstant: 'Function',
//   createMolarVolume: 'Function',
//   createNeutronMass: 'Function',
//   createNuclearMagneton: 'Function',
//   createPlanckCharge: 'Function',
//   createPlanckConstant: 'Function',
//   createPlanckLength: 'Function',
//   createPlanckMass: 'Function',
//   createPlanckTemperature: 'Function',
//   createPlanckTime: 'Function',
//   createProtonMass: 'Function',
//   createQuantumOfCirculation: 'Function',
//   createReducedPlanckConstant: 'Function',
//   createRydberg: 'Function',
//   createSackurTetrode: 'Function',
//   createSecondRadiation: 'Function',
//   createSpeedOfLight: 'Function',
//   createStefanBoltzmann: 'Function',
//   createThomsonCrossSection: 'Function',
//   createVacuumImpedance: 'Function',
//   createWeakMixingAngle: 'Function',
//   createWienDisplacement: 'Function',
//   createFilterTransform: 'Function',
//   createForEachTransform: 'Function',
//   createIndexTransform: 'Function',
//   createMapTransform: 'Function',
//   createMaxTransform: 'Function',
//   createMeanTransform: 'Function',
//   createMinTransform: 'Function',
//   createRangeTransform: 'Function',
//   createSubsetTransform: 'Function',
//   createConcatTransform: 'Function',
//   createSumTransform: 'Function'
// }

const allClasses = {
  BigNumber: 'Function',
  Chain: 'Function',
  Complex: 'Function',
  Fraction: 'Function',
  Matrix: 'Function',
  DenseMatrix: 'Function',
  SparseMatrix: 'Function',
  Spa: 'Function',
  FibonacciHeap: 'Function',
  ImmutableDenseMatrix: 'Function',
  Index: 'Function',
  Range: 'Function',
  ResultSet: 'Function',
  Unit: 'Function',
  Help: 'Function',
  Parser: 'Function'
}

const allES6Classes = {
  ...allClasses,
  Parser: 'Function'
}

const allNodeClasses = {
  AccessorNode: 'Function',
  ArrayNode: 'Function',
  AssignmentNode: 'Function',
  BlockNode: 'Function',
  ConditionalNode: 'Function',
  ConstantNode: 'Function',
  IndexNode: 'Function',
  FunctionAssignmentNode: 'Function',
  FunctionNode: 'Function',
  Node: 'Function',
  ObjectNode: 'Function',
  OperatorNode: 'Function',
  ParenthesisNode: 'Function',
  RangeNode: 'Function',
  RelationalNode: 'Function',
  SymbolNode: 'Function'
}

const allErrorClasses = {
  ArgumentsError: 'Function',
  DimensionError: 'Function',
  IndexError: 'Function'
}

const allTypeChecks = {
  isNumber: 'Function',
  isComplex: 'Function',
  isBigNumber: 'Function',
  isFraction: 'Function',
  isUnit: 'Function',
  isString: 'Function',
  isArray: 'Function',
  isMatrix: 'Function',
  isDenseMatrix: 'Function',
  isSparseMatrix: 'Function',
  isRange: 'Function',
  isIndex: 'Function',
  isBoolean: 'Function',
  isResultSet: 'Function',
  isHelp: 'Function',
  isFunction: 'Function',
  isDate: 'Function',
  isRegExp: 'Function',
  isObject: 'Function',
  isNull: 'Function',
  isUndefined: 'Function',
  isAccessorNode: 'Function',
  isArrayNode: 'Function',
  isAssignmentNode: 'Function',
  isBlockNode: 'Function',
  isConditionalNode: 'Function',
  isConstantNode: 'Function',
  isFunctionAssignmentNode: 'Function',
  isFunctionNode: 'Function',
  isIndexNode: 'Function',
  isNode: 'Function',
  isObjectNode: 'Function',
  isOperatorNode: 'Function',
  isParenthesisNode: 'Function',
  isRangeNode: 'Function',
  isSymbolNode: 'Function',
  isChain: 'Function'
}

const allFunctions = {
  config: 'Function',
  typed: 'Function',
  bignumber: 'Function',
  boolean: 'Function',
  complex: 'Function',
  fraction: 'Function',
  index: 'Function',
  matrix: 'Function',
  sparse: 'Function',
  number: 'Function',
  string: 'Function',
  unit: 'Function',
  createUnit: 'Function',
  splitUnit: 'Function',
  derivative: 'Function',
  simplify: 'Function',
  rationalize: 'Function',
  qr: 'Function',
  lup: 'Function',
  slu: 'Function',
  lsolve: 'Function',
  lusolve: 'Function',
  usolve: 'Function',
  abs: 'Function',
  add: 'Function',
  cbrt: 'Function',
  ceil: 'Function',
  cube: 'Function',
  divide: 'Function',
  dotDivide: 'Function',
  dotMultiply: 'Function',
  dotPow: 'Function',
  exp: 'Function',
  expm1: 'Function',
  fix: 'Function',
  floor: 'Function',
  gcd: 'Function',
  hypot: 'Function',
  lcm: 'Function',
  log: 'Function',
  log10: 'Function',
  log1p: 'Function',
  log2: 'Function',
  mod: 'Function',
  multiply: 'Function',
  norm: 'Function',
  nthRoot: 'Function',
  nthRoots: 'Function',
  pow: 'Function',
  round: 'Function',
  sign: 'Function',
  sqrt: 'Function',
  square: 'Function',
  subtract: 'Function',
  unaryMinus: 'Function',
  unaryPlus: 'Function',
  xgcd: 'Function',
  bitAnd: 'Function',
  bitNot: 'Function',
  bitOr: 'Function',
  bitXor: 'Function',
  leftShift: 'Function',
  rightArithShift: 'Function',
  rightLogShift: 'Function',
  bellNumbers: 'Function',
  composition: 'Function',
  stirlingS2: 'Function',
  catalan: 'Function',
  arg: 'Function',
  conj: 'Function',
  im: 'Function',
  re: 'Function',
  intersect: 'Function',
  distance: 'Function',
  and: 'Function',
  not: 'Function',
  or: 'Function',
  xor: 'Function',
  apply: 'Function',
  concat: 'Function',
  column: 'Function',
  cross: 'Function',
  ctranspose: 'Function',
  det: 'Function',
  diag: 'Function',
  dot: 'Function',
  eye: 'Function',
  expm: 'Function',
  filter: 'Function',
  flatten: 'Function',
  forEach: 'Function',
  identity: 'Function',
  inv: 'Function',
  kron: 'Function',
  map: 'Function',
  ones: 'Function',
  partitionSelect: 'Function',
  range: 'Function',
  reshape: 'Function',
  resize: 'Function',
  row: 'Function',
  size: 'Function',
  sort: 'Function',
  sqrtm: 'Function',
  squeeze: 'Function',
  subset: 'Function',
  trace: 'Function',
  transpose: 'Function',
  zeros: 'Function',
  getMatrixDataType: 'Function',
  combinations: 'Function',
  factorial: 'Function',
  gamma: 'Function',
  kldivergence: 'Function',
  multinomial: 'Function',
  permutations: 'Function',
  pickRandom: 'Function',
  random: 'Function',
  randomInt: 'Function',
  compare: 'Function',
  compareNatural: 'Function',
  compareText: 'Function',
  deepEqual: 'Function',
  equal: 'Function',
  equalText: 'Function',
  larger: 'Function',
  largerEq: 'Function',
  smaller: 'Function',
  smallerEq: 'Function',
  unequal: 'Function',
  setCartesian: 'Function',
  setDifference: 'Function',
  setDistinct: 'Function',
  setIntersect: 'Function',
  setIsSubset: 'Function',
  setMultiplicity: 'Function',
  setPowerset: 'Function',
  setSize: 'Function',
  setSymDifference: 'Function',
  setUnion: 'Function',
  erf: 'Function',
  mad: 'Function',
  max: 'Function',
  mean: 'Function',
  median: 'Function',
  min: 'Function',
  mode: 'Function',
  prod: 'Function',
  quantileSeq: 'Function',
  std: 'Function',
  sum: 'Function',
  variance: 'Function',
  format: 'Function',
  print: 'Function',
  acos: 'Function',
  acosh: 'Function',
  acot: 'Function',
  acoth: 'Function',
  acsc: 'Function',
  acsch: 'Function',
  asec: 'Function',
  asech: 'Function',
  asin: 'Function',
  asinh: 'Function',
  atan: 'Function',
  atan2: 'Function',
  atanh: 'Function',
  cos: 'Function',
  cosh: 'Function',
  cot: 'Function',
  coth: 'Function',
  csc: 'Function',
  csch: 'Function',
  sec: 'Function',
  sech: 'Function',
  sin: 'Function',
  sinh: 'Function',
  tan: 'Function',
  tanh: 'Function',
  to: 'Function',
  clone: 'Function',
  isInteger: 'Function',
  isNegative: 'Function',
  isNumeric: 'Function',
  hasNumericValue: 'Function',
  isPositive: 'Function',
  isPrime: 'Function',
  isZero: 'Function',
  isNaN: 'Function',
  typeOf: 'Function',
  compile: 'Function',
  evaluate: 'Function',
  help: 'Function',
  parse: 'Function',
  parser: 'Function',
  numeric: 'Function',
  addScalar: 'Function',
  divideScalar: 'Function',
  multiplyScalar: 'Function',
  equalScalar: 'Function',
  reviver: 'Function'
}

const allFunctionsExceptReviver = {
  ...allFunctions
}
delete allFunctionsExceptReviver.reviver

const allInstanceFunctions = {
  ...allFunctions,
  'import': 'Function',
  'var': 'Function',
  'eval': 'Function',
  'typeof': 'Function',
  typed: 'Function',
  core: 'Function',
  create: 'Function',
  chain: 'Function'
}

const allES6Functions = {
  ...allFunctions,
  typed: 'Function',
  core: 'Function',
  create: 'Function',
  factory: 'Function',
  chain: 'Function'
}

const allInstanceConstants = {
  true: 'boolean',
  false: 'boolean',
  null: 'null',
  Infinity: 'number',
  NaN: 'number',
  pi: 'number',
  tau: 'number',
  e: 'number',
  phi: 'number',
  E: 'number',
  LN2: 'number',
  LN10: 'number',
  LOG2E: 'number',
  LOG10E: 'number',
  PI: 'number',
  SQRT1_2: 'number',
  SQRT2: 'number',
  i: 'Complex',
  version: 'string'
}

const allDependencyCollections = {
  all: 'Object',
  ResultSetDependencies: 'Object',
  ComplexDependencies: 'Object',
  RangeDependencies: 'Object',
  typeofDependencies: 'Object',
  eyeDependencies: 'Object',
  NodeDependencies: 'Object',
  ArrayNodeDependencies: 'Object',
  BlockNodeDependencies: 'Object',
  ConstantNodeDependencies: 'Object',
  IndexNodeDependencies: 'Object',
  OperatorNodeDependencies: 'Object',
  RangeNodeDependencies: 'Object',
  ChainDependencies: 'Object',
  reviverDependencies: 'Object',
  falseDependencies: 'Object',
  nullDependencies: 'Object',
  trueDependencies: 'Object',
  BigNumberDependencies: 'Object',
  MatrixDependencies: 'Object',
  ConditionalNodeDependencies: 'Object',
  ObjectNodeDependencies: 'Object',
  RelationalNodeDependencies: 'Object',
  eDependencies: 'Object',
  iDependencies: 'Object',
  LN10Dependencies: 'Object',
  LOG10EDependencies: 'Object',
  NaNDependencies: 'Object',
  piDependencies: 'Object',
  SQRT1_2Dependencies: 'Object',
  tauDependencies: 'Object',
  efimovFactorDependencies: 'Object',
  fineStructureDependencies: 'Object',
  sackurTetrodeDependencies: 'Object',
  weakMixingAngleDependencies: 'Object',
  FractionDependencies: 'Object',
  ParenthesisNodeDependencies: 'Object',
  EDependencies: 'Object',
  LN2Dependencies: 'Object',
  phiDependencies: 'Object',
  SQRT2Dependencies: 'Object',
  DenseMatrixDependencies: 'Object',
  InfinityDependencies: 'Object',
  PIDependencies: 'Object',
  typedDependencies: 'Object',
  isIntegerDependencies: 'Object',
  isNumericDependencies: 'Object',
  isPositiveDependencies: 'Object',
  isNaNDependencies: 'Object',
  equalScalarDependencies: 'Object',
  numberDependencies: 'Object',
  booleanDependencies: 'Object',
  complexDependencies: 'Object',
  splitUnitDependencies: 'Object',
  unaryPlusDependencies: 'Object',
  addScalarDependencies: 'Object',
  ceilDependencies: 'Object',
  expDependencies: 'Object',
  fixDependencies: 'Object',
  log10Dependencies: 'Object',
  multiplyScalarDependencies: 'Object',
  signDependencies: 'Object',
  squareDependencies: 'Object',
  bitNotDependencies: 'Object',
  argDependencies: 'Object',
  imDependencies: 'Object',
  notDependencies: 'Object',
  filterDependencies: 'Object',
  forEachDependencies: 'Object',
  mapDependencies: 'Object',
  erfDependencies: 'Object',
  formatDependencies: 'Object',
  isPrimeDependencies: 'Object',
  acosDependencies: 'Object',
  acotDependencies: 'Object',
  acscDependencies: 'Object',
  asecDependencies: 'Object',
  asinDependencies: 'Object',
  atanDependencies: 'Object',
  atanhDependencies: 'Object',
  coshDependencies: 'Object',
  cothDependencies: 'Object',
  cschDependencies: 'Object',
  sechDependencies: 'Object',
  sinhDependencies: 'Object',
  tanhDependencies: 'Object',
  FunctionAssignmentNodeDependencies: 'Object',
  chainDependencies: 'Object',
  combinationsDependencies: 'Object',
  pickRandomDependencies: 'Object',
  randomIntDependencies: 'Object',
  LOG2EDependencies: 'Object',
  filterTransformDependencies: 'Object',
  mapTransformDependencies: 'Object',
  cloneDependencies: 'Object',
  hasNumericValueDependencies: 'Object',
  typeOfDependencies: 'Object',
  stringDependencies: 'Object',
  fractionDependencies: 'Object',
  unaryMinusDependencies: 'Object',
  cubeDependencies: 'Object',
  floorDependencies: 'Object',
  log2Dependencies: 'Object',
  sqrtDependencies: 'Object',
  conjDependencies: 'Object',
  getMatrixDataTypeDependencies: 'Object',
  modeDependencies: 'Object',
  printDependencies: 'Object',
  acoshDependencies: 'Object',
  acschDependencies: 'Object',
  asinhDependencies: 'Object',
  cosDependencies: 'Object',
  cscDependencies: 'Object',
  sinDependencies: 'Object',
  versionDependencies: 'Object',
  forEachTransformDependencies: 'Object',
  isNegativeDependencies: 'Object',
  SparseMatrixDependencies: 'Object',
  matrixDependencies: 'Object',
  cbrtDependencies: 'Object',
  gcdDependencies: 'Object',
  modDependencies: 'Object',
  nthRootDependencies: 'Object',
  xgcdDependencies: 'Object',
  bitAndDependencies: 'Object',
  bitXorDependencies: 'Object',
  orDependencies: 'Object',
  concatDependencies: 'Object',
  diagDependencies: 'Object',
  identityDependencies: 'Object',
  onesDependencies: 'Object',
  reshapeDependencies: 'Object',
  sizeDependencies: 'Object',
  subsetDependencies: 'Object',
  zerosDependencies: 'Object',
  toDependencies: 'Object',
  roundDependencies: 'Object',
  leftShiftDependencies: 'Object',
  rightLogShiftDependencies: 'Object',
  compareDependencies: 'Object',
  compareTextDependencies: 'Object',
  smallerDependencies: 'Object',
  largerDependencies: 'Object',
  unequalDependencies: 'Object',
  maxDependencies: 'Object',
  ImmutableDenseMatrixDependencies: 'Object',
  FibonacciHeapDependencies: 'Object',
  sparseDependencies: 'Object',
  acothDependencies: 'Object',
  atan2Dependencies: 'Object',
  secDependencies: 'Object',
  addDependencies: 'Object',
  traceDependencies: 'Object',
  AccessorNodeDependencies: 'Object',
  randomDependencies: 'Object',
  compositionDependencies: 'Object',
  maxTransformDependencies: 'Object',
  minTransformDependencies: 'Object',
  subsetTransformDependencies: 'Object',
  isZeroDependencies: 'Object',
  absDependencies: 'Object',
  lcmDependencies: 'Object',
  subtractDependencies: 'Object',
  bitOrDependencies: 'Object',
  xorDependencies: 'Object',
  flattenDependencies: 'Object',
  resizeDependencies: 'Object',
  transposeDependencies: 'Object',
  rightArithShiftDependencies: 'Object',
  compareNaturalDependencies: 'Object',
  equalTextDependencies: 'Object',
  largerEqDependencies: 'Object',
  partitionSelectDependencies: 'Object',
  minDependencies: 'Object',
  SpaDependencies: 'Object',
  asechDependencies: 'Object',
  tanDependencies: 'Object',
  setSizeDependencies: 'Object',
  AssignmentNodeDependencies: 'Object',
  concatTransformDependencies: 'Object',
  bignumberDependencies: 'Object',
  multiplyDependencies: 'Object',
  reDependencies: 'Object',
  kronDependencies: 'Object',
  squeezeDependencies: 'Object',
  prodDependencies: 'Object',
  powDependencies: 'Object',
  dotPowDependencies: 'Object',
  andDependencies: 'Object',
  smallerEqDependencies: 'Object',
  sortDependencies: 'Object',
  cotDependencies: 'Object',
  normDependencies: 'Object',
  sumDependencies: 'Object',
  quantileSeqDependencies: 'Object',
  gammaDependencies: 'Object',
  rangeTransformDependencies: 'Object',
  expm1Dependencies: 'Object',
  crossDependencies: 'Object',
  ctransposeDependencies: 'Object',
  equalDependencies: 'Object',
  IndexDependencies: 'Object',
  setCartesianDependencies: 'Object',
  setDistinctDependencies: 'Object',
  setIsSubsetDependencies: 'Object',
  setPowersetDependencies: 'Object',
  dotDependencies: 'Object',
  factorialDependencies: 'Object',
  permutationsDependencies: 'Object',
  indexTransformDependencies: 'Object',
  sumTransformDependencies: 'Object',
  dotMultiplyDependencies: 'Object',
  numericDependencies: 'Object',
  deepEqualDependencies: 'Object',
  setDifferenceDependencies: 'Object',
  setMultiplicityDependencies: 'Object',
  indexDependencies: 'Object',
  rangeDependencies: 'Object',
  setIntersectDependencies: 'Object',
  divideScalarDependencies: 'Object',
  nthRootsDependencies: 'Object',
  lsolveDependencies: 'Object',
  UnitDependencies: 'Object',
  createUnitDependencies: 'Object',
  hypotDependencies: 'Object',
  lupDependencies: 'Object',
  sluDependencies: 'Object',
  detDependencies: 'Object',
  distanceDependencies: 'Object',
  stirlingS2Dependencies: 'Object',
  catalanDependencies: 'Object',
  atomicMassDependencies: 'Object',
  bohrMagnetonDependencies: 'Object',
  boltzmannDependencies: 'Object',
  conductanceQuantumDependencies: 'Object',
  deuteronMassDependencies: 'Object',
  electronMassDependencies: 'Object',
  faradayDependencies: 'Object',
  firstRadiationDependencies: 'Object',
  gravitationConstantDependencies: 'Object',
  hartreeEnergyDependencies: 'Object',
  klitzingDependencies: 'Object',
  magneticConstantDependencies: 'Object',
  molarMassDependencies: 'Object',
  molarPlanckConstantDependencies: 'Object',
  neutronMassDependencies: 'Object',
  planckChargeDependencies: 'Object',
  planckLengthDependencies: 'Object',
  planckTemperatureDependencies: 'Object',
  protonMassDependencies: 'Object',
  reducedPlanckConstantDependencies: 'Object',
  secondRadiationDependencies: 'Object',
  stefanBoltzmannDependencies: 'Object',
  vacuumImpedanceDependencies: 'Object',
  logDependencies: 'Object',
  dotDivideDependencies: 'Object',
  unitDependencies: 'Object',
  SymbolNodeDependencies: 'Object',
  qrDependencies: 'Object',
  invDependencies: 'Object',
  sqrtmDependencies: 'Object',
  intersectDependencies: 'Object',
  bellNumbersDependencies: 'Object',
  avogadroDependencies: 'Object',
  classicalElectronRadiusDependencies: 'Object',
  electricConstantDependencies: 'Object',
  fermiCouplingDependencies: 'Object',
  gravityDependencies: 'Object',
  loschmidtDependencies: 'Object',
  molarMassC12Dependencies: 'Object',
  nuclearMagnetonDependencies: 'Object',
  planckMassDependencies: 'Object',
  quantumOfCirculationDependencies: 'Object',
  speedOfLightDependencies: 'Object',
  wienDisplacementDependencies: 'Object',
  log1pDependencies: 'Object',
  setSymDifferenceDependencies: 'Object',
  FunctionNodeDependencies: 'Object',
  expmDependencies: 'Object',
  bohrRadiusDependencies: 'Object',
  elementaryChargeDependencies: 'Object',
  inverseConductanceQuantumDependencies: 'Object',
  molarVolumeDependencies: 'Object',
  planckTimeDependencies: 'Object',
  thomsonCrossSectionDependencies: 'Object',
  usolveDependencies: 'Object',
  parseDependencies: 'Object',
  evaluateDependencies: 'Object',
  ParserDependencies: 'Object',
  lusolveDependencies: 'Object',
  divideDependencies: 'Object',
  medianDependencies: 'Object',
  varianceDependencies: 'Object',
  stdDependencies: 'Object',
  multinomialDependencies: 'Object',
  coulombDependencies: 'Object',
  magneticFluxQuantumDependencies: 'Object',
  rydbergDependencies: 'Object',
  setUnionDependencies: 'Object',
  evalDependencies: 'Object',
  HelpDependencies: 'Object',
  meanDependencies: 'Object',
  varDependencies: 'Object',
  simplifyDependencies: 'Object',
  rationalizeDependencies: 'Object',
  planckConstantDependencies: 'Object',
  compileDependencies: 'Object',
  helpDependencies: 'Object',
  kldivergenceDependencies: 'Object',
  gasConstantDependencies: 'Object',
  parserDependencies: 'Object',
  derivativeDependencies: 'Object',
  madDependencies: 'Object',
  meanTransformDependencies: 'Object'
}

const allES6Constants = {
  '_true': 'boolean',
  '_false': 'boolean',
  '_null': 'null',
  '_Infinity': 'number',
  '_NaN': 'number',
  pi: 'number',
  tau: 'number',
  e: 'number',
  phi: 'number',
  LN2: 'number',
  LN10: 'number',
  LOG2E: 'number',
  LOG10E: 'number',
  SQRT1_2: 'number',
  SQRT2: 'number',
  i: 'Complex',
  version: 'string'
}

const allPhysicalConstants = {
  speedOfLight: 'Unit',
  gravitationConstant: 'Unit',
  planckConstant: 'Unit',
  reducedPlanckConstant: 'Unit',
  magneticConstant: 'Unit',
  electricConstant: 'Unit',
  vacuumImpedance: 'Unit',
  coulomb: 'Unit',
  elementaryCharge: 'Unit',
  bohrMagneton: 'Unit',
  conductanceQuantum: 'Unit',
  inverseConductanceQuantum: 'Unit',
  magneticFluxQuantum: 'Unit',
  nuclearMagneton: 'Unit',
  klitzing: 'Unit',
  bohrRadius: 'Unit',
  classicalElectronRadius: 'Unit',
  electronMass: 'Unit',
  fermiCoupling: 'Unit',
  fineStructure: 'number',
  hartreeEnergy: 'Unit',
  protonMass: 'Unit',
  deuteronMass: 'Unit',
  neutronMass: 'Unit',
  quantumOfCirculation: 'Unit',
  rydberg: 'Unit',
  thomsonCrossSection: 'Unit',
  weakMixingAngle: 'number',
  efimovFactor: 'number',
  atomicMass: 'Unit',
  avogadro: 'Unit',
  boltzmann: 'Unit',
  faraday: 'Unit',
  firstRadiation: 'Unit',
  loschmidt: 'Unit',
  gasConstant: 'Unit',
  molarPlanckConstant: 'Unit',
  molarVolume: 'Unit',
  sackurTetrode: 'number',
  secondRadiation: 'Unit',
  stefanBoltzmann: 'Unit',
  wienDisplacement: 'Unit',
  molarMass: 'Unit',
  molarMassC12: 'Unit',
  gravity: 'Unit',
  planckLength: 'Unit',
  planckMass: 'Unit',
  planckTime: 'Unit',
  planckCharge: 'Unit',
  planckTemperature: 'Unit'
}

const embeddedDocs = {
  bignumber: 'Object',
  boolean: 'Object',
  complex: 'Object',
  createUnit: 'Object',
  fraction: 'Object',
  index: 'Object',
  matrix: 'Object',
  number: 'Object',
  sparse: 'Object',
  splitUnit: 'Object',
  string: 'Object',
  unit: 'Object',
  e: 'Object',
  E: 'Object',
  false: 'Object',
  i: 'Object',
  Infinity: 'Object',
  LN2: 'Object',
  LN10: 'Object',
  LOG2E: 'Object',
  LOG10E: 'Object',
  NaN: 'Object',
  null: 'Object',
  pi: 'Object',
  PI: 'Object',
  phi: 'Object',
  SQRT1_2: 'Object',
  SQRT2: 'Object',
  tau: 'Object',
  true: 'Object',
  version: 'Object',
  speedOfLight: 'Object',
  gravitationConstant: 'Object',
  planckConstant: 'Object',
  reducedPlanckConstant: 'Object',
  magneticConstant: 'Object',
  electricConstant: 'Object',
  vacuumImpedance: 'Object',
  coulomb: 'Object',
  elementaryCharge: 'Object',
  bohrMagneton: 'Object',
  conductanceQuantum: 'Object',
  inverseConductanceQuantum: 'Object',
  magneticFluxQuantum: 'Object',
  nuclearMagneton: 'Object',
  klitzing: 'Object',
  bohrRadius: 'Object',
  classicalElectronRadius: 'Object',
  electronMass: 'Object',
  fermiCoupling: 'Object',
  fineStructure: 'Object',
  hartreeEnergy: 'Object',
  protonMass: 'Object',
  deuteronMass: 'Object',
  neutronMass: 'Object',
  quantumOfCirculation: 'Object',
  rydberg: 'Object',
  thomsonCrossSection: 'Object',
  weakMixingAngle: 'Object',
  efimovFactor: 'Object',
  atomicMass: 'Object',
  avogadro: 'Object',
  boltzmann: 'Object',
  faraday: 'Object',
  firstRadiation: 'Object',
  loschmidt: 'Object',
  gasConstant: 'Object',
  molarPlanckConstant: 'Object',
  molarVolume: 'Object',
  sackurTetrode: 'Object',
  secondRadiation: 'Object',
  stefanBoltzmann: 'Object',
  wienDisplacement: 'Object',
  molarMass: 'Object',
  molarMassC12: 'Object',
  gravity: 'Object',
  planckLength: 'Object',
  planckMass: 'Object',
  planckTime: 'Object',
  planckCharge: 'Object',
  planckTemperature: 'Object',
  derivative: 'Object',
  lsolve: 'Object',
  lup: 'Object',
  lusolve: 'Object',
  simplify: 'Object',
  rationalize: 'Object',
  slu: 'Object',
  usolve: 'Object',
  qr: 'Object',
  abs: 'Object',
  add: 'Object',
  cbrt: 'Object',
  ceil: 'Object',
  cube: 'Object',
  divide: 'Object',
  dotDivide: 'Object',
  dotMultiply: 'Object',
  dotPow: 'Object',
  exp: 'Object',
  expm: 'Object',
  expm1: 'Object',
  fix: 'Object',
  floor: 'Object',
  gcd: 'Object',
  hypot: 'Object',
  lcm: 'Object',
  log: 'Object',
  log2: 'Object',
  log1p: 'Object',
  log10: 'Object',
  mod: 'Object',
  multiply: 'Object',
  norm: 'Object',
  nthRoot: 'Object',
  nthRoots: 'Object',
  pow: 'Object',
  round: 'Object',
  sign: 'Object',
  sqrt: 'Object',
  sqrtm: 'Object',
  square: 'Object',
  subtract: 'Object',
  unaryMinus: 'Object',
  unaryPlus: 'Object',
  xgcd: 'Object',
  bitAnd: 'Object',
  bitNot: 'Object',
  bitOr: 'Object',
  bitXor: 'Object',
  leftShift: 'Object',
  rightArithShift: 'Object',
  rightLogShift: 'Object',
  bellNumbers: 'Object',
  catalan: 'Object',
  composition: 'Object',
  stirlingS2: 'Object',
  config: 'Object',
  import: 'Object',
  typed: 'Object',
  arg: 'Object',
  conj: 'Object',
  re: 'Object',
  im: 'Object',
  evaluate: 'Object',
  help: 'Object',
  distance: 'Object',
  intersect: 'Object',
  and: 'Object',
  not: 'Object',
  or: 'Object',
  xor: 'Object',
  concat: 'Object',
  cross: 'Object',
  ctranspose: 'Object',
  det: 'Object',
  diag: 'Object',
  dot: 'Object',
  getMatrixDataType: 'Object',
  identity: 'Object',
  filter: 'Object',
  flatten: 'Object',
  forEach: 'Object',
  inv: 'Object',
  kron: 'Object',
  map: 'Object',
  ones: 'Object',
  partitionSelect: 'Object',
  range: 'Object',
  resize: 'Object',
  reshape: 'Object',
  size: 'Object',
  sort: 'Object',
  squeeze: 'Object',
  subset: 'Object',
  trace: 'Object',
  transpose: 'Object',
  zeros: 'Object',
  combinations: 'Object',
  factorial: 'Object',
  gamma: 'Object',
  kldivergence: 'Object',
  multinomial: 'Object',
  permutations: 'Object',
  pickRandom: 'Object',
  random: 'Object',
  randomInt: 'Object',
  compare: 'Object',
  compareNatural: 'Object',
  compareText: 'Object',
  deepEqual: 'Object',
  equal: 'Object',
  equalText: 'Object',
  larger: 'Object',
  largerEq: 'Object',
  smaller: 'Object',
  smallerEq: 'Object',
  unequal: 'Object',
  setCartesian: 'Object',
  setDifference: 'Object',
  setDistinct: 'Object',
  setIntersect: 'Object',
  setIsSubset: 'Object',
  setMultiplicity: 'Object',
  setPowerset: 'Object',
  setSize: 'Object',
  setSymDifference: 'Object',
  setUnion: 'Object',
  erf: 'Object',
  mad: 'Object',
  max: 'Object',
  mean: 'Object',
  median: 'Object',
  min: 'Object',
  mode: 'Object',
  prod: 'Object',
  quantileSeq: 'Object',
  std: 'Object',
  sum: 'Object',
  variance: 'Object',
  acos: 'Object',
  acosh: 'Object',
  acot: 'Object',
  acoth: 'Object',
  acsc: 'Object',
  acsch: 'Object',
  asec: 'Object',
  asech: 'Object',
  asin: 'Object',
  asinh: 'Object',
  atan: 'Object',
  atanh: 'Object',
  atan2: 'Object',
  cos: 'Object',
  cosh: 'Object',
  cot: 'Object',
  coth: 'Object',
  csc: 'Object',
  csch: 'Object',
  sec: 'Object',
  sech: 'Object',
  sin: 'Object',
  sinh: 'Object',
  tan: 'Object',
  tanh: 'Object',
  to: 'Object',
  clone: 'Object',
  format: 'Object',
  isNaN: 'Object',
  isInteger: 'Object',
  isNegative: 'Object',
  isNumeric: 'Object',
  hasNumericValue: 'Object',
  isPositive: 'Object',
  isPrime: 'Object',
  isZero: 'Object',
  typeOf: 'Object'
}

exports.expectedInstanceStructure = {
  on: 'Function',
  off: 'Function',
  once: 'Function',
  emit: 'Function',
  ...allTypeChecks,
  ...allClasses,
  ...allNodeClasses,
  ...allInstanceFunctions,
  ...allInstanceConstants,
  ...allPhysicalConstants,
  ...allErrorClasses,
  expression: {
    transform: {
      apply: 'Function',
      column: 'Function',
      concat: 'Function',
      filter: 'Function',
      forEach: 'Function',
      index: 'Function',
      map: 'Function',
      max: 'Function',
      mean: 'Function',
      min: 'Function',
      range: 'Function',
      row: 'Function',
      subset: 'Function',
      sum: 'Function',
      std: 'Function',
      variance: 'Function'
    },
    mathWithTransform: {
      // note that we don't have classes here,
      // only functions and constants are allowed in the editor
      ...allFunctions,
      'var': 'Function',
      'typeof': 'Function',
      'eval': 'Function',
      ...allInstanceConstants,
      ...allPhysicalConstants
    },
    // deprecated stuff:
    // docs: embeddedDocs,
    node: {
      ...allNodeClasses
    },
    parse: 'Function',
    Parser: 'Function'
  },

  // deprecated stuff:
  type: {
    ...allTypeChecks,
    ...allClasses
  },
  json: {
    reviver: 'Function'
  },
  error: {
    ...allErrorClasses
  }
}

exports.expectedES6Structure = {
  ...allES6Functions,
  ...allES6Constants,
  ...allPhysicalConstants,
  ...allES6Classes,
  ...allNodeClasses,
  ...allTypeChecks,
  ...allErrorClasses,
  ...allDependencyCollections,
  docs: embeddedDocs
}

// not all functions are available for just numbers
// we include all functions by default, and exclude the functions
// from which we know they are not available for numbers (mostly
// matrix functions)
const excludedProperties = [].concat(
  Object.keys(allPhysicalConstants),
  [
    'bignumber',
    'complex',
    'fraction',
    'index',
    // 'matrix', // FIXME: matrix should be excluded in the end (currently is a dependency of subset)
    'sparse',
    'unit',
    'createUnit',
    'splitUnit',
    'qr',
    'lup',
    'slu',
    'lsolve',
    'lusolve',
    'usolve',
    'dotDivide',
    'dotMultiply',
    'dotPow',
    'nthRoots',
    'arg',
    'conj',
    'im',
    're',
    'intersect',
    'distance',
    'concat',
    'column',
    'cross',
    'ctranspose',
    'det',
    'diag',
    'dot',
    'eye',
    'expm',
    'flatten',
    'identity',
    'inv',
    'kron',
    'ones',
    'reshape',
    'resize',
    'row',
    'size',
    'sort',
    'sqrtm',
    'squeeze',
    'trace',
    'transpose',
    'zeros',
    'getMatrixDataType',
    'kldivergence',
    'setCartesian',
    'setDifference',
    'setDistinct',
    'setIntersect',
    'setIsSubset',
    'setMultiplicity',
    'setPowerset',
    'setSize',
    'setSymDifference',
    'setUnion',
    'to',
    'i',
    'BigNumber',
    'Complex',
    'Fraction',
    'Matrix',
    'DenseMatrix',
    'SparseMatrix',
    'Spa',
    'FibonacciHeap',
    'ImmutableDenseMatrix',
    'Index',
    'Unit'
  ],
  [
    'var',
    'eval',
    'typeof'
  ],
  [
    'ComplexDependencies',
    'typeofDependencies',
    'eyeDependencies',
    'BigNumberDependencies',
    'MatrixDependencies',
    'iDependencies',
    'efimovFactorDependencies',
    'fineStructureDependencies',
    'sackurTetrodeDependencies',
    'weakMixingAngleDependencies',
    'FractionDependencies',
    'DenseMatrixDependencies',
    'complexDependencies',
    'splitUnitDependencies',
    'argDependencies',
    'imDependencies',
    'fractionDependencies',
    'conjDependencies',
    'getMatrixDataTypeDependencies',
    'SparseMatrixDependencies',
    'applyDependencies',
    'columnDependencies',
    'rowDependencies',
    'concatDependencies',
    'diagDependencies',
    'identityDependencies',
    'onesDependencies',
    'reshapeDependencies',
    'sizeDependencies',
    'zerosDependencies',
    'toDependencies',
    'ImmutableDenseMatrixDependencies',
    'FibonacciHeapDependencies',
    'sparseDependencies',
    'traceDependencies',
    'flattenDependencies',
    'resizeDependencies',
    'transposeDependencies',
    'SpaDependencies',
    'setSizeDependencies',
    'concatTransformDependencies',
    'bignumberDependencies',
    'reDependencies',
    'kronDependencies',
    'squeezeDependencies',
    'dotPowDependencies',
    'sortDependencies',
    'crossDependencies',
    'ctransposeDependencies',
    'IndexDependencies',
    'setCartesianDependencies',
    'setDistinctDependencies',
    'setIsSubsetDependencies',
    'setPowersetDependencies',
    'dotDependencies',
    'indexTransformDependencies',
    'dotMultiplyDependencies',
    'setDifferenceDependencies',
    'setMultiplicityDependencies',
    'indexDependencies',
    'setIntersectDependencies',
    'nthRootsDependencies',
    'lsolveDependencies',
    'UnitDependencies',
    'createUnitDependencies',
    'lupDependencies',
    'sluDependencies',
    'detDependencies',
    'distanceDependencies',
    'atomicMassDependencies',
    'bohrMagnetonDependencies',
    'boltzmannDependencies',
    'conductanceQuantumDependencies',
    'deuteronMassDependencies',
    'electronMassDependencies',
    'faradayDependencies',
    'firstRadiationDependencies',
    'gravitationConstantDependencies',
    'hartreeEnergyDependencies',
    'klitzingDependencies',
    'magneticConstantDependencies',
    'molarMassDependencies',
    'molarPlanckConstantDependencies',
    'neutronMassDependencies',
    'planckChargeDependencies',
    'planckLengthDependencies',
    'planckTemperatureDependencies',
    'protonMassDependencies',
    'reducedPlanckConstantDependencies',
    'secondRadiationDependencies',
    'stefanBoltzmannDependencies',
    'vacuumImpedanceDependencies',
    'dotDivideDependencies',
    'unitDependencies',
    'qrDependencies',
    'invDependencies',
    'sqrtmDependencies',
    'intersectDependencies',
    'avogadroDependencies',
    'classicalElectronRadiusDependencies',
    'electricConstantDependencies',
    'fermiCouplingDependencies',
    'gravityDependencies',
    'loschmidtDependencies',
    'molarMassC12Dependencies',
    'nuclearMagnetonDependencies',
    'planckMassDependencies',
    'quantumOfCirculationDependencies',
    'speedOfLightDependencies',
    'wienDisplacementDependencies',
    'setSymDifferenceDependencies',
    'expmDependencies',
    'bohrRadiusDependencies',
    'elementaryChargeDependencies',
    'inverseConductanceQuantumDependencies',
    'molarVolumeDependencies',
    'planckTimeDependencies',
    'thomsonCrossSectionDependencies',
    'usolveDependencies',
    'lusolveDependencies',
    'coulombDependencies',
    'magneticFluxQuantumDependencies',
    'rydbergDependencies',
    'setUnionDependencies',
    'evalDependencies',
    'varDependencies',
    'planckConstantDependencies',
    'kldivergenceDependencies',
    'gasConstantDependencies'
  ]
)

const excludedTypes = [
  'BigNumber',
  'Complex',
  'Fraction',
  'Matrix',
  'DenseMatrix',
  'SparseMatrix',
  'Spa',
  'FibonacciHeap',
  'ImmutableDenseMatrix',
  'Index',
  'Unit'
]

exports.expectedES6StructureNumber = exclude(exports.expectedES6Structure, excludedProperties)

exports.expectedInstanceStructureNumber = exclude(exports.expectedInstanceStructure, excludedProperties)
const mathWithTransform = exclude(exports.expectedInstanceStructureNumber.expression.mathWithTransform, excludedProperties)
const transform = exclude(exports.expectedInstanceStructureNumber.expression.transform, excludedProperties)
exports.expectedInstanceStructureNumber.expression = Object.assign(
  {},
  exports.expectedInstanceStructureNumber.expression,
  {
    mathWithTransform,
    transform
  }
)
exports.expectedInstanceStructureNumber.type = exclude(exports.expectedInstanceStructureNumber.type, excludedTypes)

/**
 * Create a copy of the provided `object` and delete
 * all properties listed in `excludedProperties`
 * @param {Object} object
 * @param {string[]} excludedProperties
 * @return {Object}
 */
function exclude (object, excludedProperties) {
  const strippedObject = Object.assign({}, object)

  excludedProperties.forEach(excludedProperty => {
    delete strippedObject[excludedProperty]
  })

  return strippedObject
}
