var assert = require('assert'),
    math = require('../../../index');

describe('pickMultipleRandom', function () {
  // Note: pickMultipleRandom is a convenience function generated by distribution
  // it is tested in distribution.test.js

  it('should have a function pickMultipleRandom', function () {
    assert.equal(typeof math.pickMultipleRandom, 'function');
  })

  it('should LaTeX pickMultipleRandom', function () {
    var expression = math.parse('pickMultipleRandom([1,2,3], 2)');
    assert.equal(expression.toTex(), '\\mathrm{pickMultipleRandom}\\left(\\begin{bmatrix}1\\\\2\\\\3\\\\\\end{bmatrix},2\\right)');
  });

});
