var assert = require('assert'),
    math = require('../../../index');

describe('pickRandom', function () {
  // Note: pickRandom is a convenience function generated by distribution
  // it is tested in distribution.test.js

  it('should have a function pickRandom', function () {
    assert.equal(typeof math.pickRandom, 'function');
  })
});
