var assert = require('assert'),
    math = require('../../../index');

describe('random', function () {
  // Note: random is a convenience function generated by distribution
  // it is tested in distribution.test.js

  it('should have a function random', function () {
    assert.equal(typeof math.random, 'function');
  })
});
