const assert = require('assert')
const math = require('../../../src/main')

describe('random', function () {
  // Note: random is a convenience function generated by distribution
  // it is tested in distribution.test.js

  it('should have a function random', function () {
    assert.strictEqual(typeof math.random, 'function')
  })

  it('should LaTeX random', function () {
    const expression = math.parse('random(0,1)')
    assert.strictEqual(expression.toTex(), '\\mathrm{random}\\left(0,1\\right)')
  })
})
