import 'core-js/stable'
import * as all from './factoriesAny.js'
import { create } from './core/create.js'

export default create(all)

// Note: This file is automatically generated when building math.js.
// Changes made in this file will be overwritten.
