name: Browser testing locally

on: pull_request

jobs:
  browser-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run test:browser
        env:
          CI: true
